import fs from "node:fs";
import path from "node:path";

import { describe, expect, it } from "vitest";

/**
 * The browser runtimes have to be generated by the build that serves them.
 *
 * `public/pyodide/` and `public/sqljs/` are gitignored — they are copies of
 * `node_modules`, not source — and the build script was a bare `next build`.
 * So the deployment served `/python-worker.js`, which is committed, and 404ed
 * every file it imports. Running Python sat on "Running…" for ever, because a
 * module worker whose import never resolves posts nothing back, and the SQL
 * editor failed the same way.
 *
 * These read the manifest rather than the filesystem, so they fail on a fresh
 * clone for the right reason rather than because nobody has run the copy yet.
 */

const root = path.resolve(import.meta.dirname, "..", "..");

function packageJson(): { scripts: Record<string, string> } {
  return JSON.parse(fs.readFileSync(path.join(root, "package.json"), "utf8")) as {
    scripts: Record<string, string>;
  };
}

describe("the runtime assets the browser fetches", () => {
  it("are generated by the production build", () => {
    const build = packageJson().scripts.build ?? "";
    expect(build).toContain("setup-assets");
    // Before `next build`, which is what copies `public/` into the output.
    expect(build.indexOf("setup-assets")).toBeLessThan(build.indexOf("next build"));
  });

  it("are the ones the worker and the SQL runner actually ask for", () => {
    const setup = fs.readFileSync(path.join(root, "scripts", "setup-assets.ts"), "utf8");
    const worker = fs.readFileSync(path.join(root, "public", "python-worker.js"), "utf8");
    const sqlRunner = fs.readFileSync(
      path.join(root, "src", "lib", "sql", "run-query.ts"),
      "utf8",
    );

    // The worker imports from /pyodide/, and sql.js is told to look in /sqljs/.
    expect(worker).toContain("/pyodide/");
    expect(sqlRunner).toContain("/sqljs/");
    expect(setup).toContain('path.join(PUBLIC_DIR, "pyodide")');
    expect(setup).toContain('path.join(PUBLIC_DIR, "sqljs")');
  });

  it("keeps the worker itself in source control, since nothing generates it", () => {
    expect(fs.existsSync(path.join(root, "public", "python-worker.js"))).toBe(true);
  });
});
