import { expect, test } from "@playwright/test";

/**
 * Uploaded media, from the administrator screen through to serving.
 *
 * The file used here is a real one-pixel PNG built in the test, so nothing has
 * to be committed as a binary fixture.
 */

/** A valid 1×1 PNG. */
const PNG_BASE64 =
  "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8z8BQDwAEhQGAhKmMIQAAAABJRU5ErkJggg==";

const DESCRIPTION =
  "A single dark pixel on a pale background, used only to prove the upload path works end to end.";

async function uploadPng(page: import("@playwright/test").Page, title: string) {
  await page.goto("/admin/assets");
  await page.getByLabel("File").setInputFiles({
    name: "pixel.png",
    mimeType: "image/png",
    buffer: Buffer.from(PNG_BASE64, "base64"),
  });
  await page.getByLabel("Title").fill(title);
  await page.getByLabel(/Description, or transcript/).fill(DESCRIPTION);
  await page.getByLabel("Alternative text").fill("A single dark pixel");
  await page.getByLabel("Source and licence").fill("Generated by the test suite");
  await page.getByLabel("Syllabus dot points").fill("auto.1.6");
  await page.getByRole("button", { name: "Upload" }).click();
}

test.describe("media library", () => {
  test("an administrator can upload an image and see it listed", async ({ page }) => {
    await uploadPng(page, "Test pixel");

    await expect(page.getByRole("status")).toContainText("Uploaded");
    await expect(page.getByRole("heading", { name: "Test pixel" })).toBeVisible();
    await expect(page.getByText(DESCRIPTION)).toBeVisible();
    await expect(page.getByText("Tagged: auto.1.6")).toBeVisible();
  });

  test("refuses a file that is not what it claims to be", async ({ page }) => {
    await page.goto("/admin/assets");
    await page.getByLabel("File").setInputFiles({
      name: "not-really.png",
      mimeType: "image/png",
      buffer: Buffer.from("<!doctype html><script>alert(1)</script>"),
    });
    await page.getByLabel("Title").fill("Definitely a picture");
    await page.getByLabel(/Description, or transcript/).fill(DESCRIPTION);
    await page.getByLabel("Alternative text").fill("Nothing");
    await page.getByLabel("Source and licence").fill("Test");
    await page.getByRole("button", { name: "Upload" }).click();

    await expect(page.getByText(/That file type is not accepted/)).toBeVisible();
  });

  test("insists on a description worth writing a question from", async ({ page }) => {
    await page.goto("/admin/assets");
    await page.getByLabel("File").setInputFiles({
      name: "pixel.png",
      mimeType: "image/png",
      buffer: Buffer.from(PNG_BASE64, "base64"),
    });
    await page.getByLabel("Title").fill("Too thin");
    await page.getByLabel(/Description, or transcript/).fill("A picture.");
    await page.getByLabel("Alternative text").fill("A picture");
    await page.getByLabel("Source and licence").fill("Test");
    await page.getByRole("button", { name: "Upload" }).click();

    await expect(page.getByText(/Describe what the file shows/)).toBeVisible();
  });

  test("serves the file to a signed-in user and to nobody else", async ({
    page,
    browser,
  }) => {
    await uploadPng(page, "Served pixel");

    // The list does not render the image, so the id comes from the form that
    // would remove it.
    const assetId = await page.locator('input[name="assetId"]').first().inputValue();

    const signedIn = await page.request.get(`/api/assets/${assetId}`);
    expect(signedIn.status()).toBe(200);
    expect(signedIn.headers()["content-type"]).toContain("image/png");
    expect(signedIn.headers()["x-content-type-options"]).toEqual("nosniff");

    const anonymous = await browser.newContext({
      storageState: { cookies: [], origins: [] },
    });
    const response = await anonymous.request.get(`/api/assets/${assetId}`);
    expect(response.status()).toBe(401);
    await anonymous.close();
  });

  test("the screen is reachable by an administrator", async ({ page }) => {
    await page.goto("/admin/assets");
    await expect(page.getByRole("heading", { name: "Media" })).toBeVisible();
    // The student is kept out by the same guard as the other administrator
    // screens, which admin.spec.ts covers.
  });
});
